SUPPORTED_LANGUAGES = {
    "English": "EN",
    "Persian": "FA",
    "German": "DE",
    "French": "FR",
    "Spanish": "ES",
    "Italian": "IT",
    "Russian": "RU",
    "Japanese": "JA",
    "Korean": "KO",
    "Chinese (Simplified)": "ZH",
    "Arabic": "AR",
    "Portuguese": "PT",
    "Dutch": "NL",
    "Swedish": "SV",
    "Norwegian": "NO",
    "Danish": "DA",
    "Finnish": "FI",
    "Polish": "PL",
    "Turkish": "TR",
    "Greek": "EL",
    "Hebrew": "HE",
    "Hindi": "HI",
    "Indonesian": "ID",
    "Thai": "TH",
    "Vietnamese": "VI",
}

LANGUAGE_CHOICES = [(code, name) for name, code in SUPPORTED_LANGUAGES.items()]

RECALL_INTERVALS = [
    1,
    2,
    3,
    5,
    8,
    12,
    18,
    27,
    41,
    62,
    93,
    140,
    210,
    315,
    473,
    710,
    1065,
    1598,
    2397,
    3596,
    5394,
    8091,
]
