# Generated by Django 5.1.6 on 2025-03-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leitner", "0002_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
