# Generated by Django 5.1.6 on 2025-04-14 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leitner", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="next_recall",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
