# Generated by Django 5.1.6 on 2025-04-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leitner", "0004_alter_card_next_recall"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={"ordering": ["code"]},
        ),
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(
                choices=[
                    ("EN", "English"),
                    ("FA", "Persian"),
                    ("DE", "German"),
                    ("FR", "French"),
                    ("ES", "Spanish"),
                    ("IT", "Italian"),
                    ("RU", "Russian"),
                    ("JA", "Japanese"),
                    ("KO", "Korean"),
                    ("ZH", "Chinese (Simplified)"),
                    ("AR", "Arabic"),
                    ("PT", "Portuguese"),
                    ("NL", "Dutch"),
                    ("SV", "Swedish"),
                    ("NO", "Norwegian"),
                    ("DA", "Danish"),
                    ("FI", "Finnish"),
                    ("PL", "Polish"),
                    ("TR", "Turkish"),
                    ("EL", "Greek"),
                    ("HE", "Hebrew"),
                    ("HI", "Hindi"),
                    ("ID", "Indonesian"),
                    ("TH", "Thai"),
                    ("VI", "Vietnamese"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
