# Generated by Django 5.1.6 on 2025-04-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leitner", "0005_alter_language_options_alter_language_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
