# Generated by Django 5.0.6 on 2024-07-24 10:40

from django.db import migrations
from ..constants import SUPPORTED_LANGUAGES


def populate_languages(apps, schema_editor):
    Language = apps.get_model("leitner", "Language")
    for name, code in SUPPORTED_LANGUAGES.items():
        Language.objects.get_or_create(name=name, code=code)


def remove_languages(apps, schema_editor):
    Language = apps.get_model("leitner", "Language")
    for name, code in SUPPORTED_LANGUAGES.items():
        Language.objects.filter(name=name, code=code).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("leitner", "0006_alter_box_description"),
    ]

    operations = [
        migrations.RunPython(populate_languages, remove_languages),
    ]
