# Generated by Django 5.1.6 on 2025-04-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leitner", "0007_populate_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
